import json

class CraigsData:
    """
    A list of all the supported Craigslist areas
    state->city->area->neighborhood
    """
    def __init__(self):
        self.map =  {
                    'Alabama': {'Auburn': 'http://auburn.craigslist.org/',
                                 'Birmingham': 'http://bham.craigslist.org/',
                                 'Dothan': 'http://dothan.craigslist.org/',
                                 'Florence': 'http://shoals.craigslist.org/',
                                 'Gadsden': 'http://gadsden.craigslist.org/',
                                 'Huntsville': 'http://huntsville.craigslist.org/',
                                 'Mobile': 'http://mobile.craigslist.org/',
                                 'Montgomery': 'http://montgomery.craigslist.org/',
                                 'Tuscaloosa': 'http://tuscaloosa.craigslist.org/'},
                     'Alaska': 'http://geo.craigslist.org/iso/us/ak',
                     'Arizona': {'Flagstaff': 'http://flagstaff.craigslist.org/',
                                 'Mohave County': 'http://mohave.craigslist.org/',
                                 'Phoenix': {'East Valley': 'http://phoenix.craigslist.org/evl/',
                                             'Phx North': 'http://phoenix.craigslist.org/nph/',
                                             'West Valley': 'http://phoenix.craigslist.org/wvl/',
                                             'all': 'http://phoenix.craigslist.org/'},
                                 'Prescott': 'http://prescott.craigslist.org/',
                                 'Sierra Vista': 'http://sierravista.craigslist.org/',
                                 'Tucson': 'http://tucson.craigslist.org/',
                                 'Yuma': 'http://yuma.craigslist.org/'},
                     'Arkansas': {'Fayetteville': 'http://fayar.craigslist.org/',
                                  'Fort Smith': 'http://fortsmith.craigslist.org/',
                                  'Jonesboro': 'http://jonesboro.craigslist.org/',
                                  'Little Rock': 'http://littlerock.craigslist.org/',
                                  'Texarkana': 'http://texarkana.craigslist.org/'},
                     'California': {'Bakersfield': 'http://bakersfield.craigslist.org/',
                                    'Chico': 'http://chico.craigslist.org/',
                                    'Fresno': 'http://fresno.craigslist.org/',
                                    'Gold Country': 'http://goldcountry.craigslist.org/',
                                    'Humboldt County': 'http://humboldt.craigslist.org/',
                                    'Imperial County': 'http://imperial.craigslist.org/',
                                    'Inland Empire': 'http://inlandempire.craigslist.org/',
                                    'Los Angeles': {'Antelope Valley': 'http://losangeles.craigslist.org/ant/',
                                                    'Central La': 'http://losangeles.craigslist.org/lac/',
                                                    'San Gabriel Valley': 'http://losangeles.craigslist.org/sgv/',
                                                    'Sf Valley': 'http://losangeles.craigslist.org/sfv/',
                                                    'all': 'http://losangeles.craigslist.org/'},
                                    'Mendocino County': 'http://mendocino.craigslist.org/',
                                    'Merced': 'http://merced.craigslist.org/',
                                    'Modesto': 'http://modesto.craigslist.org/',
                                    'Monterey Bay': 'http://monterey.craigslist.org/',
                                    'Orange County': 'http://orangecounty.craigslist.org/',
                                    'Palm Springs': 'http://palmsprings.craigslist.org/',
                                    'Redding': 'http://redding.craigslist.org/',
                                    'Reno': 'http://reno.craigslist.org/',
                                    'Sacramento': 'http://sacramento.craigslist.org/',
                                    'San Diego': {'City Of San Diego': 'http://sandiego.craigslist.org/csd/',
                                                  'East Sd County': 'http://sandiego.craigslist.org/esd/',
                                                  'North Sd County': 'http://sandiego.craigslist.org/nsd/',
                                                  'South Sd County': 'http://sandiego.craigslist.org/ssd/',
                                                  'all': 'http://sandiego.craigslist.org/'},
                                    'San Luis Obispo': 'http://slo.craigslist.org/',
                                    'Santa Barbara': 'http://santabarbara.craigslist.org/',
                                    'Sf Bay Area': {'East Bay': {'Alameda': '46',
                                                                 'Albany': '47',
                                                                 'Annex': '65',
                                                                 'Antioch': '113',
                                                                 'Benicia': '68',
                                                                 'Berkeley': '48',
                                                                 'Berkeley North': '49',
                                                                 'Brentwood': '142',
                                                                 'Castro Valley': '55',
                                                                 'Claremont': '66',
                                                                 'Concord': '51',
                                                                 'Danville': '52',
                                                                 'Dublin': '53',
                                                                 'El Cerrito': '47',
                                                                 'Emeryville': '112',
                                                                 'Fairfield': '154',
                                                                 'Fremont': '54',
                                                                 'Grand': '61',
                                                                 'Hayward': '55',
                                                                 'Hercules': '56',
                                                                 'Hills': '49',
                                                                 'Lafayette': '57',
                                                                 'Livermore': '53',
                                                                 'Martinez': '51',
                                                                 'Mills': '60',
                                                                 'Montclair': '63',
                                                                 'Moraga': '57',
                                                                 'Newark': '54',
                                                                 'Oakland Downtown': '58',
                                                                 'Oakland East': '59',
                                                                 'Oakland Hills': '60',
                                                                 'Oakland Lake Merritt': '61',
                                                                 'Oakland North': '62',
                                                                 'Oakland Piedmont': '63',
                                                                 'Oakland Rockridge': '66',
                                                                 'Oakland West': '64',
                                                                 'Oakley': '142',
                                                                 'Orinda': '57',
                                                                 'Pittsburg': '113',
                                                                 'Pleasant Hill': '51',
                                                                 'Pleasanton': '53',
                                                                 'Point': '65',
                                                                 'Richmond': '65',
                                                                 'San Leandro': '67',
                                                                 'San Ramon': '52',
                                                                 'Temescal': '62',
                                                                 'Union City': '54',
                                                                 'Vacaville': '154',
                                                                 'Vallejo': '68',
                                                                 'Walnut Creek': '69',
                                                                 'all': 'http://sfbay.craigslist.org/eby/'},
                                                    'North Bay': {'Belvedere': '108',
                                                                  'Corte Madera': '91',
                                                                  'Cotati': '117',
                                                                  'Fairfax': '92',
                                                                  'Greenbrae': '93',
                                                                  'Healdsburg': '155',
                                                                  'Kentfield': '94',
                                                                  'Lake County': '152',
                                                                  'Larkspur': '95',
                                                                  'Mendocino County': '153',
                                                                  'Mill Valley': '96',
                                                                  'Napa County': '97',
                                                                  'Novato': '98',
                                                                  'Petaluma': '99',
                                                                  'Rohnert Pk': '117',
                                                                  'Ross': '94',
                                                                  'Russian River': '143',
                                                                  'San Anselmo': '101',
                                                                  'San Rafael': '102',
                                                                  'Santa Rosa': '103',
                                                                  'Sausalito': '104',
                                                                  'Sebastopol': '105',
                                                                  'Sonoma': '106',
                                                                  'Tiburon': '108',
                                                                  'West Marin': '107',
                                                                  'Windsor': '155',
                                                                  'all': 'http://sfbay.craigslist.org/nby/'},
                                                    'Peninsula': {'Atherton': '70',
                                                                  'Belmont': '71',
                                                                  'Brisbane': '73',
                                                                  'Burlingame': '74',
                                                                  'Coastside/pescadero': '115',
                                                                  'Daly City': '75',
                                                                  'East Palo Alto': '76',
                                                                  'Foster City': '77',
                                                                  'Half Moon Bay': '161',
                                                                  'Los Altos': '78',
                                                                  'Menlo Park': '79',
                                                                  'Millbrae': '80',
                                                                  'Mountain View': '81',
                                                                  'Pacifica': '82',
                                                                  'Palo Alto': '83',
                                                                  'Portola Valley': '163',
                                                                  'Redwood City': '84',
                                                                  'Redwood Shores': '85',
                                                                  'San Bruno': '86',
                                                                  'San Carlos': '87',
                                                                  'San Mateo': '88',
                                                                  'South San Francisco': '89',
                                                                  'Woodside': '162',
                                                                  'all': 'http://sfbay.craigslist.org/pen/'},
                                                    'San Francisco': {'Alamo Square': '149',
                                                                      'Ashbury Hts': '5',
                                                                      'Bayview': '110',
                                                                      'Bernal Heights': '3',
                                                                      'Castro': '4',
                                                                      'Ccsf': '13',
                                                                      'Civic': '6',
                                                                      'Cole Valley': '5',
                                                                      'Cow Hollow': '17',
                                                                      'Diamond Hts': '29',
                                                                      'Downtown': '6',
                                                                      'Excelsior': '7',
                                                                      'Financial District': '8',
                                                                      'Forest Hill': '114',
                                                                      'Glen Park': '9',
                                                                      'Haight Ashbury': '11',
                                                                      'Hayes Valley': '12',
                                                                      'Ingleside': '13',
                                                                      'Inner Richmond': '14',
                                                                      'Inner Sunset': '15',
                                                                      'Laurel Hts': '16',
                                                                      'Lower Haight': '10',
                                                                      'Lower Nob Hill': '20',
                                                                      'Lower Pac Hts': '24',
                                                                      'Marina': '17',
                                                                      'Mission District': '18',
                                                                      'Nob Hill': '19',
                                                                      'Noe Valley': '21',
                                                                      'Nopa': '149',
                                                                      'North Beach': '22',
                                                                      'Outer Mission': '7',
                                                                      'Pacific Heights': '23',
                                                                      'Panhandle': '2',
                                                                      'Parkside': '28',
                                                                      'Portola District': '164',
                                                                      'Potrero Hill': '25',
                                                                      'Presidio': '16',
                                                                      'Richmond': '26',
                                                                      'Russian Hill': '27',
                                                                      'Seacliff': '26',
                                                                      'Sfsu': '13',
                                                                      'Soma': '1',
                                                                      'South Beach': '1',
                                                                      'Sunset': '28',
                                                                      'Telegraph Hill': '22',
                                                                      'Tenderloin': '156',
                                                                      'Treasure Island': '157',
                                                                      'Twin Peaks': '29',
                                                                      'Ucsf': '15',
                                                                      'Upper Market': '4',
                                                                      'Usf': '2',
                                                                      'Van Ness': '6',
                                                                      'Visitacion Valley': '118',
                                                                      'West Portal': '114',
                                                                      'Western Addition': '30',
                                                                      'all': 'http://sfbay.craigslist.org/sfc/'},
                                                    'Santa Cruz': {'Aptos': '144',
                                                                   'Boulder Creek': '148',
                                                                   'Capitola': '145',
                                                                   'Hollister': '158',
                                                                   'Santa Cruz': '42',
                                                                   'Scotts Valley': '146',
                                                                   'Soquel': '151',
                                                                   'Watsonville': '147',
                                                                   'all': 'http://sfbay.craigslist.org/scz/'},
                                                    'South Bay': {'Cambrian': '45',
                                                                  'Campbell': '31',
                                                                  'Cupertino': '32',
                                                                  'Gilroy': '33',
                                                                  'Los Gatos': '34',
                                                                  'Milpitas': '109',
                                                                  'Morgan Hill': '119',
                                                                  'Mountain View': '35',
                                                                  'San Jose Downtown': '36',
                                                                  'San Jose East': '37',
                                                                  'San Jose North': '38',
                                                                  'San Jose South': '39',
                                                                  'San Jose West': '40',
                                                                  'Santa Clara': '41',
                                                                  'Saratoga': '43',
                                                                  'Sunnyvale': '44',
                                                                  'Willow Glen': '45',
                                                                  'all': 'http://sfbay.craigslist.org/sby/'},
                                                    'all': 'http://sfbay.craigslist.org/'},
                                    'Stockton': 'http://stockton.craigslist.org/',
                                    'Ventura County': 'http://ventura.craigslist.org/',
                                    'Visalia': 'http://visalia.craigslist.org/',
                                    'Yuba': 'http://yubasutter.craigslist.org/'},
                     'Colorado': {'Boulder': 'http://boulder.craigslist.org/',
                                  'Colorado Springs': 'http://cosprings.craigslist.org/',
                                  'Denver': 'http://denver.craigslist.org/',
                                  'Fort Collins': 'http://fortcollins.craigslist.org/',
                                  'Pueblo': 'http://pueblo.craigslist.org/',
                                  'Rocky Mountains': 'http://rockies.craigslist.org/',
                                  'Western Slope': 'http://westslope.craigslist.org/'},
                     'Connecticut': {'Eastern Ct': 'http://newlondon.craigslist.org/',
                                     'Hartford': 'http://hartford.craigslist.org/',
                                     'New Haven': 'http://newhaven.craigslist.org/',
                                     'Northwest Ct': 'http://nwct.craigslist.org/'},
                     'Dc': 'http://geo.craigslist.org/iso/us/dc',
                     'Delaware': 'http://geo.craigslist.org/iso/us/de',
                     'Florida': {'Daytona Beach': 'http://daytona.craigslist.org/',
                                 'Florida Keys': 'http://keys.craigslist.org/',
                                 'Ft Myers': 'http://fortmyers.craigslist.org/',
                                 'Gainesville': 'http://gainesville.craigslist.org/',
                                 'Jacksonville': 'http://jacksonville.craigslist.org/',
                                 'Lakeland': 'http://lakeland.craigslist.org/',
                                 'Ocala': 'http://ocala.craigslist.org/',
                                 'Orlando': 'http://orlando.craigslist.org/',
                                 'Panama City': 'http://panamacity.craigslist.org/',
                                 'Pensacola': 'http://pensacola.craigslist.org/',
                                 'Sarasota': 'http://sarasota.craigslist.org/',
                                 'South Florida': {'Broward County': 'http://miami.craigslist.org/brw/',
                                                   'Palm Beach Co': 'http://miami.craigslist.org/pbc/',
                                                   'all': 'http://miami.craigslist.org/'},
                                 'Space Coast': 'http://spacecoast.craigslist.org/',
                                 'St Augustine': 'http://staugustine.craigslist.org/',
                                 'Tallahassee': 'http://tallahassee.craigslist.org/',
                                 'Tampa Bay Area': {'Hernando Co': 'http://tampa.craigslist.org/hdo/',
                                                    'Hillsborough Co': 'http://tampa.craigslist.org/hil/',
                                                    'Pasco Co': 'http://tampa.craigslist.org/psc/',
                                                    'Pinellas Co': 'http://tampa.craigslist.org/pnl/',
                                                    'all': 'http://tampa.craigslist.org/'},
                                 'Treasure Coast': 'http://treasure.craigslist.org/'},
                     'Georgia': {'Athens': 'http://athensga.craigslist.org/',
                                 'Atlanta': 'http://atlanta.craigslist.org/',
                                 'Augusta': 'http://augusta.craigslist.org/',
                                 'Brunswick': 'http://brunswick.craigslist.org/',
                                 'Columbus': 'http://columbusga.craigslist.org/',
                                 'Macon': 'http://macon.craigslist.org/',
                                 'Savannah': 'http://savannah.craigslist.org/',
                                 'Valdosta': 'http://valdosta.craigslist.org/'},
                     'Hawaii': 'http://geo.craigslist.org/iso/us/hi',
                     'Idaho': {'Boise': 'http://boise.craigslist.org/',
                               'East Idaho': 'http://eastidaho.craigslist.org/',
                               'Pullman': 'http://pullman.craigslist.org/',
                               'Twin Falls': 'http://twinfalls.craigslist.org/'},
                     'Illinois': {'Bloomington': 'http://bn.craigslist.org/',
                                  'Carbondale': 'http://carbondale.craigslist.org/',
                                  'Champaign Urbana': 'http://chambana.craigslist.org/',
                                  'Chicago': {'City Of Chicago': 'http://chicago.craigslist.org/chc/',
                                              'North Chicagoland': 'http://chicago.craigslist.org/nch/',
                                              'Northwest Indiana': 'http://chicago.craigslist.org/nwi/',
                                              'Northwest Suburbs': 'http://chicago.craigslist.org/nwc/',
                                              'South Chicagoland': 'http://chicago.craigslist.org/sox/',
                                              'West Chicagoland': 'http://chicago.craigslist.org/wcl/',
                                              'all': 'http://chicago.craigslist.org/'},
                                  'Decatur': 'http://decatur.craigslist.org/',
                                  'Peoria': 'http://peoria.craigslist.org/',
                                  'Rockford': 'http://rockford.craigslist.org/',
                                  'Springfield': 'http://springfieldil.craigslist.org/'},
                     'Indiana': {'Bloomington': 'http://bloomington.craigslist.org/',
                                 'Evansville': 'http://evansville.craigslist.org/',
                                 'Fort Wayne': 'http://fortwayne.craigslist.org/',
                                 'Indianapolis': 'http://indianapolis.craigslist.org/',
                                 'Lafayette': 'http://tippecanoe.craigslist.org/',
                                 'Muncie': 'http://muncie.craigslist.org/',
                                 'South Bend': 'http://southbend.craigslist.org/',
                                 'Terre Haute': 'http://terrahaute.craigslist.org/'},
                     'Iowa': {'Ames': 'http://ames.craigslist.org/',
                              'Cedar Rapids': 'http://cedarrapids.craigslist.org/',
                              'Des Moines': 'http://desmoines.craigslist.org/',
                              'Dubuque': 'http://dubuque.craigslist.org/',
                              'Iowa City': 'http://iowacity.craigslist.org/',
                              'Sioux City': 'http://siouxcity.craigslist.org/',
                              'Waterloo': 'http://waterloo.craigslist.org/'},
                     'Kansas': {'Lawrence': 'http://lawrence.craigslist.org/',
                                'Manhattan': 'http://ksu.craigslist.org/',
                                'Topeka': 'http://topeka.craigslist.org/',
                                'Wichita': 'http://wichita.craigslist.org/'},
                     'Kentucky': {'Bowling Green': 'http://bgky.craigslist.org/',
                                  'Huntington': 'http://huntington.craigslist.org/',
                                  'Lexington': 'http://lexington.craigslist.org/',
                                  'Louisville': 'http://louisville.craigslist.org/',
                                  'Western Ky': 'http://westky.craigslist.org/'},
                     'Louisiana': {'Baton Rouge': 'http://batonrouge.craigslist.org/',
                                   'Lafayette': 'http://lafayette.craigslist.org/',
                                   'Lake Charles': 'http://lakecharles.craigslist.org/',
                                   'Monroe': 'http://monroe.craigslist.org/',
                                   'New Orleans': 'http://neworleans.craigslist.org/',
                                   'Shreveport': 'http://shreveport.craigslist.org/'},
                     'Maine': 'http://geo.craigslist.org/iso/us/me',
                     'Maryland': {'Annapolis': 'http://annapolis.craigslist.org/',
                                  'Baltimore': 'http://baltimore.craigslist.org/',
                                  'Eastern Shore': 'http://easternshore.craigslist.org/',
                                  'Southern Maryland': 'http://smd.craigslist.org/',
                                  'Western Maryland': 'http://westmd.craigslist.org/'},
                     'Mass': {'Boston': {'Metro West': 'http://boston.craigslist.org/bmw/',
                                         'North Shore': 'http://boston.craigslist.org/nos/',
                                         'South Shore': 'http://boston.craigslist.org/sob/',
                                         'all': 'http://boston.craigslist.org/'},
                              'Cape Cod': 'http://capecod.craigslist.org/',
                              'South Coast': 'http://southcoast.craigslist.org/',
                              'Western Massachusetts': 'http://westernmass.craigslist.org/',
                              'Worcester': 'http://worcester.craigslist.org/'},
                     'Michigan': {'Ann Arbor': 'http://annarbor.craigslist.org/',
                                  'Central Michigan': 'http://centralmich.craigslist.org/',
                                  'Detroit Metro': 'http://detroit.craigslist.org/',
                                  'Flint': 'http://flint.craigslist.org/',
                                  'Grand Rapids': 'http://grandrapids.craigslist.org/',
                                  'Jackson': 'http://jxn.craigslist.org/',
                                  'Kalamazoo': 'http://kalamazoo.craigslist.org/',
                                  'Lansing': 'http://lansing.craigslist.org/',
                                  'Muskegon': 'http://muskegon.craigslist.org/',
                                  'Northern Michigan': 'http://nmi.craigslist.org/',
                                  'Port Huron': 'http://porthuron.craigslist.org/',
                                  'South Bend': 'http://southbend.craigslist.org/',
                                  'Southwest Michigan': 'http://swmi.craigslist.org/',
                                  'Upper Peninsula': 'http://up.craigslist.org/'},
                     'Minnesota': {'Duluth': 'http://duluth.craigslist.org/',
                                   'Fargo': 'http://fargo.craigslist.org/',
                                   'Mankato': 'http://mankato.craigslist.org/',
                                   'Rochester': 'http://rmn.craigslist.org/',
                                   'St Cloud': 'http://stcloud.craigslist.org/'},
                     'Mississippi': {'Gulfport': 'http://gulfport.craigslist.org/',
                                     'Hattiesburg': 'http://hattiesburg.craigslist.org/',
                                     'Jackson': 'http://jackson.craigslist.org/',
                                     'North Mississippi': 'http://northmiss.craigslist.org/'},
                     'Missouri': {'Columbia': 'http://columbiamo.craigslist.org/',
                                  'Joplin': 'http://joplin.craigslist.org/',
                                  'Kansas City': 'http://kansascity.craigslist.org/',
                                  'Southeast Missouri': 'http://semo.craigslist.org/',
                                  'Springfield': 'http://springfield.craigslist.org/',
                                  'St Louis': 'http://stlouis.craigslist.org/'},
                     'Montana': 'http://geo.craigslist.org/iso/us/mt',
                     'N Carolina': {'Asheville': 'http://asheville.craigslist.org/',
                                    'Boone': 'http://boone.craigslist.org/',
                                    'Charlotte': 'http://charlotte.craigslist.org/',
                                    'Eastern Nc': 'http://eastnc.craigslist.org/',
                                    'Fayetteville': 'http://fayetteville.craigslist.org/',
                                    'Greensboro': 'http://greensboro.craigslist.org/',
                                    'Hickory': 'http://hickory.craigslist.org/',
                                    'Outer Banks': 'http://outerbanks.craigslist.org/',
                                    'Wilmington': 'http://wilmington.craigslist.org/',
                                    'Winston': 'http://winstonsalem.craigslist.org/'},
                     'N Hampshire': 'http://geo.craigslist.org/iso/us/nh',
                     'Nebraska': {'Grand Island': 'http://grandisland.craigslist.org/',
                                  'Lincoln': 'http://lincoln.craigslist.org/'},
                     'Nevada': {'Las Vegas': 'http://lasvegas.craigslist.org/',
                                'Reno': 'http://reno.craigslist.org/'},
                     'New Jersey': {'Central Nj': 'http://cnj.craigslist.org/',
                                    'Jersey Shore': 'http://jerseyshore.craigslist.org/',
                                    'North Jersey': 'http://newjersey.craigslist.org/',
                                    'South Jersey': 'http://southjersey.craigslist.org/'},
                     'New Mexico': {'Albuquerque': 'http://albuquerque.craigslist.org/',
                                    'Farmington': 'http://farmington.craigslist.org/',
                                    'Las Cruces': 'http://lascruces.craigslist.org/',
                                    'Roswell': 'http://roswell.craigslist.org/',
                                    'Santa Fe': 'http://santafe.craigslist.org/'},
                     'New York': {'Albany': 'http://albany.craigslist.org/',
                                  'Binghamton': 'http://binghamton.craigslist.org/',
                                  'Buffalo': 'http://buffalo.craigslist.org/',
                                  'Catskills': 'http://catskills.craigslist.org/',
                                  'Chautauqua': 'http://chautauqua.craigslist.org/',
                                  'Elmira': 'http://elmira.craigslist.org/',
                                  'Hudson Valley': 'http://hudsonvalley.craigslist.org/',
                                  'Ithaca': 'http://ithaca.craigslist.org/',
                                  'Long Island': 'http://longisland.craigslist.org/',
                                  'New York City': {'Bronx': 'http://newyork.craigslist.org/brx/',
                                                    'Brooklyn': 'http://newyork.craigslist.org/brk/',
                                                    'Fairfield': 'http://newyork.craigslist.org/fct/',
                                                    'Long Island': 'http://newyork.craigslist.org/lgi/',
                                                    'Manhattan': {'Battery Park': '120',
                                                                  'Bowery': '125',
                                                                  'Chelsea': '134',
                                                                  'Chinatown': '160',
                                                                  'Downtown': '121',
                                                                  'East Harlem': '159',
                                                                  'East Village': '129',
                                                                  'Financial District': '122',
                                                                  'Flatiron': '133',
                                                                  'Gramercy': '132',
                                                                  'Greenwich Village': '127',
                                                                  'Harlem': '141',
                                                                  'Inwood': '140',
                                                                  'Lit Italy': '160',
                                                                  'Lower East Side': '126',
                                                                  'Midtown': '135',
                                                                  'Midtown East': '136',
                                                                  'Midtown West': '137',
                                                                  'Morningside': '141',
                                                                  'Murray Hill': '131',
                                                                  'Nolita': '125',
                                                                  'Soho': '124',
                                                                  'Tribeca': '123',
                                                                  'Union Square': '130',
                                                                  'Upper East Side': '139',
                                                                  'Upper West Side': '138',
                                                                  'Wash Hts': '140',
                                                                  'West Village': '128',
                                                                  'all': 'http://newyork.craigslist.org/mnh/'},
                                                    'New Jersey': 'http://newyork.craigslist.org/jsy/',
                                                    'Queens': 'http://newyork.craigslist.org/que/',
                                                    'Staten Island': 'http://newyork.craigslist.org/stn/',
                                                    'Westchester': 'http://newyork.craigslist.org/wch/',
                                                    'all': 'http://newyork.craigslist.org/'},
                                  'Plattsburgh': 'http://plattsburgh.craigslist.org/',
                                  'Rochester': 'http://rochester.craigslist.org/',
                                  'Syracuse': 'http://syracuse.craigslist.org/',
                                  'Utica': 'http://utica.craigslist.org/',
                                  'Watertown': 'http://watertown.craigslist.org/'},
                     'North Dakota': {'Fargo': 'http://fargo.craigslist.org/',
                                      'North Dakota': 'http://nd.craigslist.org/'},
                     'Ohio': {'Akron': 'http://akroncanton.craigslist.org/',
                              'Athens': 'http://athensohio.craigslist.org/',
                              'Cincinnati': 'http://cincinnati.craigslist.org/',
                              'Cleveland': 'http://cleveland.craigslist.org/',
                              'Columbus': 'http://columbus.craigslist.org/',
                              'Dayton': 'http://dayton.craigslist.org/',
                              'Huntington': 'http://huntington.craigslist.org/',
                              'Lima': 'http://limaohio.craigslist.org/',
                              'Mansfield': 'http://mansfield.craigslist.org/',
                              'Parkersburg': 'http://parkersburg.craigslist.org/',
                              'Sandusky': 'http://sandusky.craigslist.org/',
                              'Toledo': 'http://toledo.craigslist.org/',
                              'Youngstown': 'http://youngstown.craigslist.org/'},
                     'Oklahoma': {'Lawton': 'http://lawton.craigslist.org/',
                                  'Oklahoma City': 'http://oklahomacity.craigslist.org/',
                                  'Stillwater': 'http://stillwater.craigslist.org/',
                                  'Tulsa': 'http://tulsa.craigslist.org/'},
                     'Oregon': {'Bend': 'http://bend.craigslist.org/',
                                'Corvallis': 'http://corvallis.craigslist.org/',
                                'East Oregon': 'http://eastoregon.craigslist.org/',
                                'Eugene': 'http://eugene.craigslist.org/',
                                'Oregon Coast': 'http://oregoncoast.craigslist.org/',
                                'Portland': {'Clackamas Co': 'http://portland.craigslist.org/clc/',
                                             'Columbia Gorge': 'http://portland.craigslist.org/grg/',
                                             'Multnomah Co': 'http://portland.craigslist.org/mlt/',
                                             'North Coast': 'http://portland.craigslist.org/nco/',
                                             'Washington Co': 'http://portland.craigslist.org/wsc/',
                                             'Yamhill Co': 'http://portland.craigslist.org/yam/',
                                             'all': 'http://portland.craigslist.org/'},
                                'Roseburg': 'http://roseburg.craigslist.org/',
                                'Salem': 'http://salem.craigslist.org/'},
                     'Pennsylvania': {'Altoona': 'http://altoona.craigslist.org/',
                                      'Erie': 'http://erie.craigslist.org/',
                                      'Harrisburg': 'http://harrisburg.craigslist.org/',
                                      'Lancaster': 'http://lancaster.craigslist.org/',
                                      'Lehigh Valley': 'http://allentown.craigslist.org/',
                                      'Philadelphia': 'http://philadelphia.craigslist.org/',
                                      'Pittsburgh': 'http://pittsburgh.craigslist.org/',
                                      'Poconos': 'http://poconos.craigslist.org/',
                                      'Reading': 'http://reading.craigslist.org/',
                                      'State College': 'http://pennstate.craigslist.org/',
                                      'Williamsport': 'http://williamsport.craigslist.org/',
                                      'York': 'http://york.craigslist.org/'},
                     'Rhode Island': 'http://geo.craigslist.org/iso/us/ri',
                     'S Carolina': {'Charleston': 'http://charleston.craigslist.org/',
                                    'Columbia': 'http://columbia.craigslist.org/',
                                    'Florence': 'http://florencesc.craigslist.org/',
                                    'Greenville': 'http://greenville.craigslist.org/',
                                    'Hilton Head': 'http://hiltonhead.craigslist.org/',
                                    'Myrtle Beach': 'http://myrtlebeach.craigslist.org/'},
                     'South Dakota': 'http://geo.craigslist.org/iso/us/sd',
                     'Tennessee': {'Chattanooga': 'http://chattanooga.craigslist.org/',
                                   'Clarksville': 'http://clarksville.craigslist.org/',
                                   'Jackson': 'http://jacksontn.craigslist.org/',
                                   'Knoxville': 'http://knoxville.craigslist.org/',
                                   'Memphis': 'http://memphis.craigslist.org/',
                                   'Nashville': 'http://nashville.craigslist.org/',
                                   'Tri': 'http://tricities.craigslist.org/'},
                     'Texas': {'Abilene': 'http://abilene.craigslist.org/',
                               'Amarillo': 'http://amarillo.craigslist.org/',
                               'Austin': 'http://austin.craigslist.org/',
                               'Beaumont': 'http://beaumont.craigslist.org/',
                               'Brownsville': 'http://brownsville.craigslist.org/',
                               'College Station': 'http://collegestation.craigslist.org/',
                               'Corpus Christi': 'http://corpuschristi.craigslist.org/',
                               'El Paso': 'http://elpaso.craigslist.org/',
                               'Galveston': 'http://galveston.craigslist.org/',
                               'Houston': 'http://houston.craigslist.org/',
                               'Laredo': 'http://laredo.craigslist.org/',
                               'Lubbock': 'http://lubbock.craigslist.org/',
                               'Mcallen': 'http://mcallen.craigslist.org/',
                               'Odessa': 'http://odessa.craigslist.org/',
                               'San Antonio': 'http://sanantonio.craigslist.org/',
                               'San Marcos': 'http://sanmarcos.craigslist.org/',
                               'Texarkana': 'http://texarkana.craigslist.org/',
                               'Tyler': 'http://easttexas.craigslist.org/',
                               'Victoria': 'http://victoriatx.craigslist.org/',
                               'Waco': 'http://waco.craigslist.org/',
                               'Wichita Falls': 'http://wichitafalls.craigslist.org/'},
                     'Utah': {'Logan': 'http://logan.craigslist.org/',
                              'Ogden': 'http://ogden.craigslist.org/',
                              'Provo': 'http://provo.craigslist.org/',
                              'Salt Lake City': 'http://saltlakecity.craigslist.org/',
                              'St George': 'http://stgeorge.craigslist.org/'},
                     'Vermont': 'http://geo.craigslist.org/iso/us/vt',
                     'Virginia': {'Blacksburg': 'http://blacksburg.craigslist.org/',
                                  'Charlottesville': 'http://charlottesville.craigslist.org/',
                                  'Danville': 'http://danville.craigslist.org/',
                                  'Eastern Shore': 'http://easternshore.craigslist.org/',
                                  'Fredericksburg': 'http://fredericksburg.craigslist.org/',
                                  'Hampton Roads': 'http://norfolk.craigslist.org/',
                                  'Harrisonburg': 'http://harrisonburg.craigslist.org/',
                                  'Lynchburg': 'http://lynchburg.craigslist.org/',
                                  'Richmond': 'http://richmond.craigslist.org/',
                                  'Roanoke': 'http://roanoke.craigslist.org/'},
                     'Washington': {'Bellingham': 'http://bellingham.craigslist.org/',
                                    'Olympic Peninsula': 'http://olympic.craigslist.org/',
                                    'Pullman': 'http://pullman.craigslist.org/',
                                    'Wenatchee': 'http://wenatchee.craigslist.org/',
                                    'Yakima': 'http://yakima.craigslist.org/'},
                     'West Virginia': {'Charleston': 'http://charlestonwv.craigslist.org/',
                                       'Huntington': 'http://huntington.craigslist.org/',
                                       'Martinsburg': 'http://martinsburg.craigslist.org/',
                                       'Morgantown': 'http://morgantown.craigslist.org/',
                                       'Parkersburg': 'http://parkersburg.craigslist.org/',
                                       'Wheeling': 'http://wheeling.craigslist.org/'},
                     'Wisconsin': {'Duluth': 'http://duluth.craigslist.org/',
                                   'Eau Claire': 'http://eauclaire.craigslist.org/',
                                   'Green Bay': 'http://greenbay.craigslist.org/',
                                   'Janesville': 'http://janesville.craigslist.org/',
                                   'Kenosha': 'http://racine.craigslist.org/',
                                   'La Crosse': 'http://lacrosse.craigslist.org/',
                                   'Madison': 'http://madison.craigslist.org/',
                                   'Milwaukee': 'http://milwaukee.craigslist.org/',
                                   'Sheboygan': 'http://sheboygan.craigslist.org/',
                                   'Wausau': 'http://wausau.craigslist.org/'},
                     'Wyoming': 'http://geo.craigslist.org/iso/us/wy'
                    }
        self.categories = {'Community': {'sections': {'Activities': 'act',
                                                    'Artists': 'ats',
                                                    'Childcare': 'kid',
                                                    'Community': 'ccc',
                                                    'Events': 'cal',
                                                    'General': 'com',
                                                    'Groups': 'grp',
                                                    'Musicians': 'muc',
                                                    'Pets': 'pet',
                                                    'Politics': 'pol',
                                                    'Rideshare': 'rid',
                                                    'Volunteers': 'vol'},
                                       'url': 'ccc'},
                         'For Sale': {'sections': {'Antiques': 'atq',
                                                   'Appliances': 'app',
                                                   'Auto Parts': 'pts',
                                                   'Barter': 'bar',
                                                   'Bikes': 'bik',
                                                   'Boats': 'boa',
                                                   'Books': 'bks',
                                                   'Business': 'bfs',
                                                   'Cds/dvd/vhs': 'emd',
                                                   'Cell Phones': 'mob',
                                                   'Collectibles': 'clt',
                                                   'Computer': 'sys',
                                                   'Electronics': 'ele',
                                                   'For Sale': 'sss',
                                                   'Free': 'zip',
                                                   'Furniture': 'fua',
                                                   'Garage Sale': 'gms',
                                                   'General': 'for',
                                                   'Household': 'hsh',
                                                   'Jewelry': 'jwl',
                                                   'Materials': 'mat',
                                                   'Motorcycles': 'mcy',
                                                   'Music Instr': 'msg',
                                                   'Rvs': 'rvs',
                                                   'Sporting': 'spo',
                                                   'Tickets': 'tix',
                                                   'Tools': 'tls',
                                                   'Video Gaming': 'vgm',
                                                   'Wanted': 'wan'},
                                      'url': 'sss'},
                         'Gigs': {'sections': {'Adult': 'adg'}, 'url': 'ggg'},
                         'Housing': {'sections': {'Apts / Housing': 'apa',
                                                  'Housing': 'hhh',
                                                  'Housing Swap': 'swp',
                                                  'Housing Wanted': 'hsw',
                                                  'Office / Commercial': 'off',
                                                  'Parking / Storage': 'prk',
                                                  'Real Estate For Sale': 'rea',
                                                  'Rooms / Shared': 'roo',
                                                  'Sublets / Temporary': 'sub',
                                                  'Vacation Rentals': 'vac'},
                                     'url': 'hhh'},
                         'Jobs': {'sections': {'Admin / Office': 'ofc',
                                               'Arch / Engineering': 'egr',
                                               'Art / Media / Design': 'med',
                                               'Biotech / Science': 'sci',
                                               'Business / Mgmt': 'bus',
                                               'Customer Service': 'csr',
                                               'Education': 'edu',
                                               'Food / Bev / Hosp': 'fbh',
                                               'General Labor': 'lab',
                                               'Government': 'gov',
                                               'Human Resources': 'hum',
                                               'Internet Engineers': 'eng',
                                               'Jobs': 'jjj',
                                               'Legal / Paralegal': 'lgl',
                                               'Manufacturing': 'mnu',
                                               'Marketing / Pr / Ad': 'mar',
                                               'Medical / Health': 'hea',
                                               'Nonprofit Sector': 'npo',
                                               'Real Estate': 'rej',
                                               'Retail / Wholesale': 'ret',
                                               'Sales / Biz Dev': 'sls',
                                               'Salon / Spa / Fitness': 'spa',
                                               'Security': 'sec',
                                               'Skilled Trade / Craft': 'trd',
                                               'Software / Qa / Dba': 'sof',
                                               'Systems / Network': 'sad',
                                               'Technical Support': 'tch',
                                               'Transport': 'trp',
                                               'Tv / Film / Video': 'tfr',
                                               'Web / Info Design': 'web',
                                               'Writing / Editing': 'wri'},
                                  'url' : 'jjj'},
                           'Personals':{'sections':{}}}
    def json(self):
        return json.dumps(self.map)
